language: node_js
node_js:
- 14
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4a2166934298_key -iv $encrypted_4a2166934298_iv
  -in .travis/id_rsa_github_io.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'lixingcong'
- git config --global user.email 'lixingcong@live.com'
- git submodule update --init --recursive
install:
- npm install -g hexo-cli
- npm install hexo-util js-yaml --save
before_script:
- hexo init hexo-empty-dir
- cd hexo-empty-dir
- npm install
- function linkFileHere { [ -f $1 ] && mv $1 $1.bak; ln -s ../$1 ./$1; }
- linkFileHere source
- linkFileHere themes
- linkFileHere deploy.sh
- linkFileHere _config.yml
- linkFileHere _config.next.yml
script:
- hexo g && bash deploy.sh
